### ISSUE TITLE
attr 'half_pixel_centers' not in Op<name=ResizeBilinear; signature=images:T, size:int32 -> resized_images:float

### ISSUE THREAD

**Issue by IvyGongoogle** [tensorflow/tensorrt#41] opened 2019-03-14 07:31 UTC
hello, I  open a `tensorflow/serving` according to  [this](https://medium.com/tensorflow/optimizing-tensorflow-serving-performance-with-nvidia-tensorrt-6d8a2347869a) 
after I do `Convert and serve the model with TF-TRT`, finally when I run `python /tmp/resnet/resnet_client.py`, the `tensorflow/serving` shows error:

```
2019-03-14 07:25:19.809001: I tensorflow_serving/model_servers/server.cc:333] Exporting HTTP/REST API at:localhost:8501 ...
2019-03-14 07:25:57.612330: E external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:624] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'half_pixel_centers' not in Op<name=ResizeBilinear; signature=images:T, size:int32 -> resized_images:float; attr=T:type,allowed=[DT_INT8, DT_UINT8, DT_INT16, DT_UINT16, DT_INT32, DT_INT64, DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE]; attr=align_corners:bool,default=false>; NodeDef: {{node map/while/resize_images/ResizeBilinear}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[{{node map/while/resize_images/ResizeBilinear}}]]
```

how to fix it? anyone can give some advises?

**Comment by pooyadavoodi** [comment] 2019-03-14 17:37
Perhaps you need to regenerate the graph with the same version of TF that you are using to run it?

**Comment by IvyGongoogle** [comment] 2019-03-17 12:45
@pooyadavoodi thanks for your reply. Now I use the newest `tensorflow-gpu 2.0.0a0` to train a `resnet-50` model  using  the [tutorial ](https://github.com/tensorflow/models/tree/master/official/resnet). Then I optimize my `resnet-50`graph by running: 

```
docker run --rm --runtime=nvidia -it \
    -v /tmp:/tmp tensorflow/tensorflow:nightly-gpu \
    /usr/local/bin/saved_model_cli convert \
    --dir /tmp/resnet-50/xxx \
    --output_dir /tmp/resnet-50_trt/xxx \
    --tag_set serve \
    tensorrt --precision_mode FP32 --max_batch_size 1 --is_dynamic_op True
```
it shows error:

```
There are 5 ops of 4 different types in the graph that are not converted to TensorRT: Softmax, ArgMax, Placeholder, NoOp, (For more information see https://docs.nvidia.com/deeplearning/dgx/integrate-tf-trt/index.html#support-ops).
2019-03-17 12:28:11.672181: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:824] Number of TensorRT candidate segments: 1
2019-03-17 12:28:11.984280: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-03-17 12:28:12.108886: I tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc:924] TensorRT node resnet_model/TRTEngineOp_0 added for segment 0 consisting of 465 nodes succeeded.
2019-03-17 12:28:12.221444: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:666] Optimization results for grappler item: tf_graph
2019-03-17 12:28:12.221521: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:668]   constant folding: Graph size after: 472 nodes (-267), 487 edges (-267), time = 615.238ms.
2019-03-17 12:28:12.221534: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:668]   layout: Graph size after: 472 nodes (0), 487 edges (0), time = 154.866ms.
2019-03-17 12:28:12.221560: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:668]   constant folding: Graph size after: 472 nodes (0), 487 edges (0), time = 266.192ms.
2019-03-17 12:28:12.221587: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:668]   TensorRTOptimizer: Graph size after: 8 nodes (-464), 7 edges (-480), time = 842.931ms.
```
and the dir ` /tmp/resnet-50_trt/xxx/variables/` is empty, which has no `variables.data-00000-of-00001` and  `variables.index`. So this convert failed?   And all ops in this graph must be supported by tensorrt if we use tensorrt to optimize our tf model graph?

looking forward to your reply.

**Comment by IvyGongoogle** [comment] 2019-03-23 11:02
need help...

**Comment by pooyadavoodi** [comment] 2019-03-25 17:22
Could you share the TF Log of the conversion?

+@aaroey

**Comment by aaroey** [comment] 2019-03-25 17:28
Hi @IvyGongoogle, its expected that the variables/ dir is empty since TF-TRT converts all the variables to constants and embeds them in the graph (aka saved_model.pb). But, did you encounter any errors because of that?

**Comment by IvyGongoogle** [comment] 2019-03-28 09:11
@pooyadavoodi @aaroey  as you said, TF-TRT converts all the variables to constants and embeds them in the graph (aka saved_model.pb). Now this  `saved_model.pb` can be serving by tensorflow serving, but I am just wondering why only a single frozen graph pb file can be served by tensorflow serving?

**Comment by aaroey** [comment] 2019-03-28 14:06
@IvyGongoogle not sure if I understand your question. A SavedModel contains the GraphDef, input/output signatures and other metadata, and optional variables and other assets. It's more than a frozen graph pb file which is only a serialized GraphDef. 

Since the original problem is solved I'm closing this issue, feel free to reopen if there are any questions. Thanks.

**Closed by aaroey** 2019-03-28 14:06 UTC

**Comment by vijeshkpaei** [comment] 2019-05-02 14:10
install tensorflow nightly

**Comment by GuruRChandran6s** [comment] 2019-06-26 11:10
I am running the resnet model in docker optimized with Tensor-rt. I am getting 
status = StatusCode.INVALID_ARGUMENT
details = "NodeDef mentions attr 'explicit_paddings' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_BFLOAT16, DT_FLOAT, DT_DOUBLE]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]; attr=dilations:list(int),default=[1, 1, 1, 1]>; NodeDef: {{node FirstStageFeatureExtractor/resnet_v1_101/resnet_v1_101/conv1/Conv2D}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

My tensorflow version is 1.13.1. This model is trained some 8 months ago so not sure about the tf version used at that time. I used docker saved_model_cli to optimize the model using tensorrt. Kindly help

**Comment by arbala22** [comment] 2019-07-12 11:58
I have faced below issue while use the exported tensorflow model  for inference from 1.12 version. 

ValueError: NodeDef mentions attr 'half_pixel_centers' not in Op<name=ResizeBilinear; signature=images:T, size:int32 -> resized_images:float; attr=T:type,allowed=[DT_INT8, DT_UINT8, DT_INT16, DT_UINT16, DT_INT32, DT_INT64, DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE]; attr=align_corners:bool,default=false>; NodeDef: {{node Preprocessor/map/while/ResizeImage/resize/ResizeBilinear}} = ResizeBilinear[T=DT_FLOAT, align_corners=false, half_pixel_centers=false](Preprocessor/map/while/ResizeImage/resize/ExpandDims, Preprocessor/map/while/ResizeImage/stack). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

If trained and created checkpoint in 1.12 version and exported the model from v1.4 , i can able use the tensorflow model without flaw...

**Comment by gogasca** [comment] 2019-07-17 20:54
These are the steps to reproduce in TF 1.14.0
```
wget http://download.tensorflow.org/models/official/20181001_resnet/savedmodels/resnet_v2_fp32_savedmodel_NCHW_jpg.tar.gz
tar -xzvf resnet_v2_fp32_savedmodel_NCHW_jpg.tar.gz

# Convert to TensorRT model:

import tensorflow.contrib.tensorrt as trt

BATCH_SIZE=128
PRECISION_MODE='FP16'
SAVED_MODEL_PATH='resnet_v2_fp32_savedmodel_NCHW_jpg/1538687370'
TRT_SAVED_MODEL_PATH='trt_resnet_v2_fp16_savedmodel_NCHW_jpg/1'
DYNAMIC_OP=True

trt.create_inference_graph(
    None,
    None,
    is_dynamic_op=DYNAMIC_OP,
    max_batch_size=BATCH_SIZE,
    precision_mode=PRECISION_MODE,
    input_saved_model_dir=SAVED_MODEL_PATH,
    output_saved_model_dir=TRT_SAVED_MODEL_PATH) 

export MODEL_DIR=trt_resnet_v2_fp16_savedmodel_NCHW_jpg/
./tensorflow_model_server --rest_api_port=8501 --model_base_path="${MODEL_DIR}"
```
Then send requests with resnet_client.py


```2019-07-17 20:50:31.263967: E external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:624] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'half_pixel_centers' not in Op<name=ResizeBilinear; signature=images:T, size:int32 -> resized_images:float; attr=T:type,allowed=[DT_INT8, DT_UINT8, DT_INT16, DT_UINT16, DT_INT32, DT_INT64, DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE]; attr=align_corners:bool,default=false>; NodeDef: {{node map/while/resize_images/ResizeBilinear}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[{{node map/while/resize_images/ResizeBilinear}}]]
```

**Comment by aaroey** [comment] 2019-07-23 16:53
@gogasca I think the reason is https://github.com/tensorflow/tensorflow/commit/3ae2c6691b7c6e0986d97b150c9283e5cc52c15f added the half_pixel_centers attribute to the op and the change is in the most recent release, but your model was built in 2018 so the graph doesn't contain that attribute. I think this is not related to TF-TRT.

**Comment by Mohandfares** [comment] 2020-06-07 11:52
Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: NodeDef mentions attr 'half_pixel_centers' not in Op<name=ResizeBilinear; signature=images:T, size:int32 -> resized_images:float; attr=T:type,allowed=[DT_INT8, DT_UINT8, DT_INT16, DT_UINT16, DT_INT32, DT_INT64, DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE]; attr=align_corners:bool,default=false>; NodeDef: {{node Preprocessor/map/while/ResizeImage/resize/ResizeBilinear}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
