### ISSUE TITLE
TF-TRT can not deal with dynamic_rnn, right?

### ISSUE THREAD

**Issue by MachineJeff** [tensorflow/tensorrt#154] opened 2019-11-18 10:23 UTC
Hi 
I have tested TensoRT in my model so mant times, but always failed.
After debug the model, I suspect that TensorRT can not deal with dynamic_rnn, because in dynamic_rnn, `tf.while_loop` is called.

**Comment by rmccorm4** [comment] 2019-11-18 19:40
(Duplicate of https://github.com/NVIDIA/TensorRT/issues/226)

Hi @MachineJeff,

Unfortunately the parsers do not currently support this. This is related to: https://github.com/NVIDIA/TensorRT/issues/220#issuecomment-554110947

At the moment, I think it is possible to implement directly through the TensorRT API, but you would need to save your model's weights (numpy arrays), create the model from scratch using the TensorRT API, and then load them: https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/python_api/infer/Graph/Layers.html#rnn-layers

**Comment by MachineJeff** [comment] 2019-11-19 02:20
Solved. 
disscussion is in [NVIDIA/TensorRT#226](https://github.com/NVIDIA/TensorRT/issues/226).

**Closed** 2019-11-19 02:20 UTC
